- name: A requalifier
  color: e6ad1c
  description: ""

- name: backend
  color: E28B67
  description: ""

- name: config
  color: 73A99E
  description: ""

- name: documentation
  color: 0075ca
  description: ""

- name: Pre-MDM
  color: dcc497
  description: ""

- name: Test Clichy
  color: c5def5
  description: ""

- name: ✅ C'est tout bon
  color: 0e8a16
  description: ""

- name: 🕦 Attente du MDM
  color: 640440
  description: ""

- name: 😩 Toujours pas bon
  color: 440c09
  description: ""
