---
name: Bug
description: Signaler un bug
projects:
  - pulse-web-interface
type: Bug
body:
  - type: markdown
    attributes:
      value: Merci de remplir ces champs !
  - type: input
    id: url
    attributes:
      label: Url de la page
      description: "Aides-nous à localiser le problème. Pour les devs : il est
        possible d'indiquer le chemin relatif vers le composant"
      placeholder: https:pulse-xr.com/page-avec-bug
    validations:
      required: false
  - type: textarea
    id: bug-description
    attributes:
      label: Quel est le problème ?
    validations:
      required: true
