---
name: 💣 Bug
description: Signaler un bug

type: Bug
body:
 - type: dropdown
    id: project
    attributes:
      label: "Périmètre"
      options:
        - Web
        - Appli mobile
        - Mdm
        - Autre (préciser dans la description du problème, et l'option sera ajoutée !)
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Url de la page
      description: "Aides-nous à localiser le problème."
      placeholder: https:pulse-xr.com/page-avec-bug
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Décris-nous le problème le plus précisement possible.
    validations:
      required: true
