---
name: 🚀 Feature
description: Demander une nouvelle fonctionnalité et/ou une amélioration
type: Feature
body:
  - type: dropdown
    id: project
    attributes:
      label: "Périmètre"
      options:
        - Web
        - Appli mobile
        - Mdm
        - Autre (préciser dans la description du problème, et l'option sera ajoutée !)
    validations:
      required: true
  - type: checkboxes
    id: type-feature
    attributes:
      label: "Préciser le type de la demande"
      options:
        - label: Amélioration
        - label: Nouvelle fonctionnalité
  - type: input
    id: url
    attributes:
      label: "Url de la page"
      description: "Aides-nous à localiser le problème."
      placeholder: "https://pulse-xr.com/page-avec-bug"
    validations:
      required: false
  - type: textarea
    id: feature-detailed
    attributes:
      label: "Description complète de la demande"
      description: "Un résumé de la fonctionnalité ou de l'amélioration demandée. N'hésite pas à ajouter une ou plusieurs captures d'écran"
    validations:
      required: true

