---
name: 📌 Task
description: Prévoir une tâche hors bug ou nouvelle fonctionnalité (tests, configuration, traduction, etc)
type: Task
body:
  - type: dropdown
    id: project
    attributes:
      label: "Périmètre"
      options:
        - 💻 Interface web
        - 📱 Appli mobile
        - 🧩 Mdm
        - 🥽 Appli VR
        - Autre (préciser dans la description du problème, et l'option sera ajoutée !)
    validations:
      required: true
  - type: checkboxes
    id: type-feature
    attributes:
      label: "Préciser le type de la tâche. (Si aucune option ne correspond, choisir 'Autre' et indiquer le type dans le champ de description)"
      options:
        - label: Tests
        - label: Traduction
        - label: Sécurité
        - label: Configuration
        - label: Factorisation
        - label: Autre
  - type: input
    id: url
    attributes:
      label: "Cible"
      description: "Aides-nous à localiser le problème."
      placeholder: "https://pulse-xr.com/page-avec-bug"
    validations:
      required: false
  - type: textarea
    id: feature-detailed
    attributes:
      label: "Description complète de la tâche"
      description: "Un résumé de la tâche demandée. N'hésite pas à ajouter une ou plusieurs captures d'écran"
    validations:
      required: true
