# This is a basic workflow to help you get started with Actions

name: PR Labeler

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types: [opened, reopened]
  issues:
    types: [labeled, unlabeled]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: PR labeler
        uses: SteveG-tkorp/test-actions@v0.0.1-alpha
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          pr_number: "${{ github.event.pull_request.number }}"
        env:
          ACTIONS_STEP_DEBUG: true

