name: PR Labeler
on:
  pull_request:
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PR labeler
        uses: SteveG-tkorp/test-actions@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}
          labels_config_path: "./.github/workflows/labeler-config.json"
